### ISSUE TITLE
Wrong src url in luarocks file

### ISSUE THREAD

**Issue by fmaksim74** [pkulchenko/serpent#42]
In serpent-scm-1.rockspec file used SSH URL for src value. It required SSL authorization that cannot be done if sudo in use.
The src value need to be changed to HTTPS url.
Thanks.

**Comment by pkulchenko** [comment]
Fixed; thanks!

**Comment by fmaksim74** [comment]
Still cannot be installed:
`Error: Couldn't extract archive serpent.git: unrecognized filename extension`
It seems like have to remove `.git` extension from url.

**Comment by pkulchenko** [comment]
It looks like it should be `git+https://github.com/pkulchenko/serpent`, at least judging by rockspec docs and [this presentation](https://www.lua.org/wshop18/Muhammad.pdf).

**Comment by potchy** [comment]
I'm still getting an error:

```
luarocks install serpent 0.30-1
Installing https://luarocks.org/serpent-0.30-1.rockspec

Error: Couldn't extract archive C:\Users\vitor\AppData\Local\Temp/luarocks_luarocks-source-serpent-0.30-1-2768/serpent.git: unrecognized filename extension
```

**Comment by folknor** [comment]
Same problem for me as @potchy using the latest `luarocks` compiled from git for lua5.4 installing to `$HOME/.luarocks` on debian:
```
$ luarocks install serpent
Installing https://luarocks.org/serpent-0.30-1.rockspec

Error: Couldn't extract archive /tmp/luarocks_luarocks-source-serpent-0.30-1-aelBii/serpent.git: unrecognized filename extension
```

**Comment by pkulchenko** [comment]
Should be fixed now both in the repository and in luarocks: https://luarocks.org/modules/paulclinger/serpent.

**Comment by folknor** [comment]
Yes, works now, thank you :+1:
